swagger: '2.0'

info:
  version: "1.0.0"
  title: AssijusSystem
  description: Micro-serviço para listar documentos, obter o hash, salvar assinaturas e visualizar PDFs compatível com o sistema Assijus

# host: assijus.jfrj.jus.br
basePath: /tnusigner/api/v1
schemes: [http]
consumes: [application/json]
produces: [application/json]

tags:
  - name: view
    description: Listar os documentos a serem assinado e visualizar os PDFs
  - name: sign
    description: Obter o hash e gravar a assinatura digital

paths:
  /doc/list:
    get:
      description: Obter a lista de documentos a serem assinados pelo usuário portador do CPF informado
      tags: [view,sign]
      parameters:
        - $ref: "#/parameters/cpf" 
        - $ref: "#/parameters/urlapi" 
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              list:
                type: array
                items:
                  $ref: "#/definitions/Document"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
  /doc/{id}/pdf:
    get:
      description: Obter o PDF de um documento para visualização
      tags: [view]
      parameters:
        - $ref: "#/parameters/id"
        - $ref: "#/parameters/cpf" 
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              doc:
                type: string
                format: byte
                description: PDF codificado em base64
            example:
              doc: 24yd3pPUpPz4dyVdRQAP+zI7R8wTsNX9J7El/a5Bb64=
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
  /doc/{id}/hash:
    get:
      description: Obter o hash de um documento
      tags: [sign]
      parameters:
        - $ref: "#/parameters/id"
        - $ref: "#/parameters/cpf" 
        - $ref: "#/parameters/extra" 
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              sha1:
                type: string
                format: byte
              sha256:
                type: string
                format: byte
              policy:
                type: string
              extra:
                type: string
              doc:
                type: string
                format: byte
            example:      
              sha1: csTZGGSt1AG1m3T5VaIzcHX8Av0=
              sha256: 24yd3pPUpPz4dyVdRQAP+zI7R8wTsNX9J7El/a5Bb64=
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
  /doc/{id}/sign:
    put:
      description: Gravar a assinatura do documento
      tags: [sign]
      parameters:
        - $ref: "#/parameters/id"
        - $ref: "#/parameters/cpf" 
        - $ref: "#/parameters/name" 
        - $ref: "#/parameters/time" 
        - $ref: "#/parameters/sha1" 
        - $ref: "#/parameters/extra" 
        - $ref: "#/parameters/envelope" 
      responses:
        200:
          description: Successful response
          schema:
            type: object
            properties:
              status:
                type: string
              warning:
                type: array
                items:
                  $ref: "#/definitions/Warning"
        500:
          description: Error ocurred
          schema:
            $ref: "#/definitions/Error"
            
parameters:
  id:
    name: id
    in: path
    description: Identificador do documento
    required: true
    type: string
  cpf:
    name: cpf
    in: query
    description: CPF do usuário
    required: true
    type: string
  urlapi:
    name: urlapi
    in: query
    description: DEPRECATED - URL que foi usada para chamar a API.
    required: false
    type: string
  sha1:
    name: sha1
    required: false
    type: string
    format: byte
  sha256:
    name: sha256
    required: false
    type: string
    format: byte
  name:
    name: name
    required: false
    type: string
  time:
    name: time
    required: false
    type: string
    format: date-time
  envelope:
    name: envelope
    in: formData
    description: Envelope CMS/PKCS7 codificado em base64
    required: true
    type: string
    format: byte
  extra:
    name: extra
    required: false
    type: string

            
definitions:
  Document:
    type: object
    properties:
      id:
        type: string
        description: identificador do documento
      code: 
        type: string
      descr: 
        type: string
      kind: 
        type: string
      origin: 
        type: string
      extra: 
        type: string
    example:
      id: 00489623760_2_67631650_1460490840000_0_0
      code: 0100222-90.2014.4.02.0000
      descr: Conclusão para Decisão  -  Concedida a Antecipação de tutela
      kind: Decisão
      origin: TextoWeb
      extra: 1

  Warning:
    type: object
    properties:
      label:
        type: string
      description:
        type: string

  Error:
    type: object
    properties:
      error:
        type: string
